training_name: constant
dataset_base_path: "dvc/datasets/guardian"
training_base_path: "dvc/trainings/guardian_months"
evaluation_base_path: "dvc/evaluations/guardian_months"
model_name: "constant"
selected_trainings:
- dvc/trainings/guardian_months/2000-03/world/constant
- dvc/trainings/guardian_months/2000-05/world/constant
- dvc/trainings/guardian_months/2000-06/world/constant
- dvc/trainings/guardian_months/2000-10/world/constant
- dvc/trainings/guardian_months/2001-01/world/constant
- dvc/trainings/guardian_months/2001-02/world/constant
- dvc/trainings/guardian_months/2001-04/world/constant
- dvc/trainings/guardian_months/2001-09/world/constant
- dvc/trainings/guardian_months/2001-10/uk-news/constant
- dvc/trainings/guardian_months/2001-10/world/constant
- dvc/trainings/guardian_months/2002-07/world/constant
- dvc/trainings/guardian_months/2002-11/world/constant
- dvc/trainings/guardian_months/2002-12/world/constant
- dvc/trainings/guardian_months/2007-05/world/constant
- dvc/trainings/guardian_months/2007-07/uk-news/constant
- dvc/trainings/guardian_months/2007-07/world/constant
- dvc/trainings/guardian_months/2007-10/world/constant
- dvc/trainings/guardian_months/2008-02/world/constant
- dvc/trainings/guardian_months/2008-05/world/constant
- dvc/trainings/guardian_months/2008-09/world/constant
- dvc/trainings/guardian_months/2008-10/world/constant
- dvc/trainings/guardian_months/2010-01/world/constant
- dvc/trainings/guardian_months/2010-04/us-news/constant
- dvc/trainings/guardian_months/2010-04/world/constant
- dvc/trainings/guardian_months/2010-08/us-news/constant
- dvc/trainings/guardian_months/2010-08/world/constant
- dvc/trainings/guardian_months/2010-10/world/constant
- dvc/trainings/guardian_months/2010-12/us-news/constant
- dvc/trainings/guardian_months/2010-12/world/constant
- dvc/trainings/guardian_months/2011-04/us-news/constant
- dvc/trainings/guardian_months/2011-05/us-news/constant
- dvc/trainings/guardian_months/2012-04/uk-news/constant
- dvc/trainings/guardian_months/2012-07/us-news/constant
- dvc/trainings/guardian_months/2012-07/world/constant
- dvc/trainings/guardian_months/2012-11/world/constant
- dvc/trainings/guardian_months/2014-02/world/constant
- dvc/trainings/guardian_months/2014-03/world/constant
- dvc/trainings/guardian_months/2014-05/world/constant
- dvc/trainings/guardian_months/2014-06/world/constant
- dvc/trainings/guardian_months/2014-07/world/constant
- dvc/trainings/guardian_months/2015-04/us-news/constant
- dvc/trainings/guardian_months/2015-06/us-news/constant
- dvc/trainings/guardian_months/2015-09/uk-news/constant
- dvc/trainings/guardian_months/2015-10/us-news/constant
- dvc/trainings/guardian_months/2016-01/us-news/constant
- dvc/trainings/guardian_months/2016-03/us-news/constant
- dvc/trainings/guardian_months/2016-06/uk-news/constant
- dvc/trainings/guardian_months/2016-11/us-news/constant
- dvc/trainings/guardian_months/2019-03/us-news/constant
- dvc/trainings/guardian_months/2019-03/world/constant
- dvc/trainings/guardian_months/2019-04/world/constant
- dvc/trainings/guardian_months/2019-06/world/constant
- dvc/trainings/guardian_months/2019-07/world/constant
- dvc/trainings/guardian_months/2019-09/world/constant
- dvc/trainings/guardian_months/2019-10/us-news/constant
- dvc/trainings/guardian_months/2019-11/world/constant
- dvc/trainings/guardian_months/2019-12/uk-news/constant
- dvc/trainings/guardian_months/2019-12/us-news/constant
- dvc/trainings/guardian_months/2020-01/world/constant
- dvc/trainings/guardian_months/2020-03/world/constant
- dvc/trainings/guardian_months/2020-04/world/constant
- dvc/trainings/guardian_months/2020-05/us-news/constant
- dvc/trainings/guardian_months/2020-06/world/constant
- dvc/trainings/guardian_months/2020-08/world/constant
- dvc/trainings/guardian_months/2020-09/us-news/constant
- dvc/trainings/guardian_months/2020-09/world/constant
- dvc/trainings/guardian_months/2020-10/us-news/constant
- dvc/trainings/guardian_months/2020-11/us-news/constant
- dvc/trainings/guardian_months/2020-11/world/constant
- dvc/trainings/guardian_months/2021-01/uk-news/constant
- dvc/trainings/guardian_months/2021-01/us-news/constant
- dvc/trainings/guardian_months/2021-02/world/constant
- dvc/trainings/guardian_months/2021-05/us-news/constant
- dvc/trainings/guardian_months/2021-06/world/constant
- dvc/trainings/guardian_months/2021-08/world/constant
- dvc/trainings/guardian_months/2021-09/us-news/constant
- dvc/trainings/guardian_months/2021-10/world/constant
- dvc/trainings/guardian_months/2022-02/world/constant
- dvc/trainings/guardian_months/2022-03/world/constant
- dvc/trainings/guardian_months/2022-05/world/constant
- dvc/trainings/guardian_months/2022-06/us-news/constant
- dvc/trainings/guardian_months/2022-07/world/constant
- dvc/trainings/guardian_months/2022-08/us-news/constant
- dvc/trainings/guardian_months/2022-12/world/constant

selected_events:
- dvc/events/guardian/2000/world.csv
- dvc/events/guardian/2000/world.csv
- dvc/events/guardian/2000/world.csv
- dvc/events/guardian/2000/world.csv
- dvc/events/guardian/2001/world.csv
- dvc/events/guardian/2001/world.csv
- dvc/events/guardian/2001/world.csv
- dvc/events/guardian/2001/world.csv
- dvc/events/guardian/2001/uk-news.csv
- dvc/events/guardian/2001/world.csv
- dvc/events/guardian/2002/world.csv
- dvc/events/guardian/2002/world.csv
- dvc/events/guardian/2002/world.csv
- dvc/events/guardian/2007/world.csv
- dvc/events/guardian/2007/uk-news.csv
- dvc/events/guardian/2007/world.csv
- dvc/events/guardian/2007/world.csv
- dvc/events/guardian/2008/world.csv
- dvc/events/guardian/2008/world.csv
- dvc/events/guardian/2008/world.csv
- dvc/events/guardian/2008/world.csv
- dvc/events/guardian/2010/world.csv
- dvc/events/guardian/2010/us-news.csv
- dvc/events/guardian/2010/world.csv
- dvc/events/guardian/2010/us-news.csv
- dvc/events/guardian/2010/world.csv
- dvc/events/guardian/2010/world.csv
- dvc/events/guardian/2010/us-news.csv
- dvc/events/guardian/2010/world.csv
- dvc/events/guardian/2011/us-news.csv
- dvc/events/guardian/2011/us-news.csv
- dvc/events/guardian/2012/uk-news.csv
- dvc/events/guardian/2012/us-news.csv
- dvc/events/guardian/2012/world.csv
- dvc/events/guardian/2012/world.csv
- dvc/events/guardian/2014/world.csv
- dvc/events/guardian/2014/world.csv
- dvc/events/guardian/2014/world.csv
- dvc/events/guardian/2014/world.csv
- dvc/events/guardian/2014/world.csv
- dvc/events/guardian/2015/us-news.csv
- dvc/events/guardian/2015/us-news.csv
- dvc/events/guardian/2015/uk-news.csv
- dvc/events/guardian/2015/us-news.csv
- dvc/events/guardian/2016/us-news.csv
- dvc/events/guardian/2016/us-news.csv
- dvc/events/guardian/2016/uk-news.csv
- dvc/events/guardian/2016/us-news.csv
- dvc/events/guardian/2019/us-news.csv
- dvc/events/guardian/2019/world.csv
- dvc/events/guardian/2019/world.csv
- dvc/events/guardian/2019/world.csv
- dvc/events/guardian/2019/world.csv
- dvc/events/guardian/2019/world.csv
- dvc/events/guardian/2019/us-news.csv
- dvc/events/guardian/2019/world.csv
- dvc/events/guardian/2019/uk-news.csv
- dvc/events/guardian/2019/us-news.csv
- dvc/events/guardian/2020/world.csv
- dvc/events/guardian/2020/world.csv
- dvc/events/guardian/2020/world.csv
- dvc/events/guardian/2020/us-news.csv
- dvc/events/guardian/2020/world.csv
- dvc/events/guardian/2020/world.csv
- dvc/events/guardian/2020/us-news.csv
- dvc/events/guardian/2020/world.csv
- dvc/events/guardian/2020/us-news.csv
- dvc/events/guardian/2020/us-news.csv
- dvc/events/guardian/2020/world.csv
- dvc/events/guardian/2021/uk-news.csv
- dvc/events/guardian/2021/us-news.csv
- dvc/events/guardian/2021/world.csv
- dvc/events/guardian/2021/us-news.csv
- dvc/events/guardian/2021/world.csv
- dvc/events/guardian/2021/world.csv
- dvc/events/guardian/2021/us-news.csv
- dvc/events/guardian/2021/world.csv
- dvc/events/guardian/2022/world.csv
- dvc/events/guardian/2022/world.csv
- dvc/events/guardian/2022/world.csv
- dvc/events/guardian/2022/us-news.csv
- dvc/events/guardian/2022/world.csv
- dvc/events/guardian/2022/us-news.csv
- dvc/events/guardian/2022/world.csv

processes:
