training_name: distilroberta
dataset_base_path: "dvc/datasets/guardian_extended"
training_base_path: "dvc/trainings/guardian_months"
evaluation_base_path: "dvc/evaluations/guardian_months"
model_name: "distilroberta"
selected_trainings: [
    "dvc/trainings/guardian_months/2001-08-24-2001-10-09/world/distilroberta",
    "dvc/trainings/guardian_months/2008-08-24-2008-10-09/world/distilroberta",
    "dvc/trainings/guardian_months/2016-05-24-2016-07-09/uk-news/distilroberta",
    "dvc/trainings/guardian_months/2016-10-24-2016-12-09/us-news/distilroberta",
    "dvc/trainings/guardian_months/2020-10-24-2020-12-09/us-news/distilroberta",
    "dvc/trainings/guardian_months/2020-12-24-2021-02-09/us-news/distilroberta",
    "dvc/trainings/guardian_months/2021-07-24-2021-09-09/world/distilroberta",
    "dvc/trainings/guardian_months/2022-05-24-2022-07-09/us-news/distilroberta",
    "dvc/trainings/guardian_months/2022-01-24-2022-03-09/world/distilroberta",
    "dvc/trainings/guardian_months/2000-11-23-2001-01-09/us-news/distilroberta",
    "dvc/trainings/guardian_months/2002-11-23-2003-01-09/world/distilroberta",
    "dvc/trainings/guardian_months/2014-05-24-2014-07-09/world/distilroberta",
    "dvc/trainings/guardian_months/2020-07-24-2020-09-09/world/distilroberta"
]
selected_events: [
    "dvc/events/guardian_months/2000-7-1_2002-6-30/world.csv",
    "dvc/events/guardian_months/2007-7-1_2009-6-30/world.csv",
    "dvc/events/guardian_months/2015-7-1_2017-6-30/uk-news.csv",
    "dvc/events/guardian_months/2015-7-1_2017-6-30/us-news.csv",
    "dvc/events/guardian_months/2019-7-1_2021-6-30/us-news.csv",
    "dvc/events/guardian_months/2020-7-1_2022-6-30/us-news.csv",
    "dvc/events/guardian_months/2020-7-1_2022-6-30/world.csv",
    "dvc/events/guardian_months/2021-7-1_2023-6-30/us-news.csv",
    "dvc/events/guardian_months/2021-7-1_2023-6-30/world.csv",
    "dvc/events/guardian_months/1999-7-1_2001-6-30/us-news.csv",
    "dvc/events/guardian_months/2001-7-1_2003-6-30/world.csv",
    "dvc/events/guardian_months/2013-7-1_2015-6-30/world.csv",
    "dvc/events/guardian_months/2019-7-1_2021-6-30/world.csv",
]
processes:
