training_name: distilroberta
dataset_base_path: "dvc/datasets/guardian"
training_base_path: "dvc/trainings/guardian_months"
evaluation_base_path: "dvc/evaluations/guardian_months"
model_name: "distilroberta"
selected_trainings: [
    "dvc/trainings/guardian_months/2001-09/world/distilroberta",
    "dvc/trainings/guardian_months/2008-09/world/distilroberta",
    "dvc/trainings/guardian_months/2016-06/uk-news/distilroberta",
    "dvc/trainings/guardian_months/2016-11/us-news/distilroberta",
    "dvc/trainings/guardian_months/2020-11/us-news/distilroberta",
    "dvc/trainings/guardian_months/2021-01/us-news/distilroberta",
    "dvc/trainings/guardian_months/2021-08/world/distilroberta",
    "dvc/trainings/guardian_months/2022-06/us-news/distilroberta",
    "dvc/trainings/guardian_months/2022-02/world/distilroberta",
    "dvc/trainings/guardian_months/2002-12/world/distilroberta",
    "dvc/trainings/guardian_months/2014-06/world/distilroberta",
    "dvc/trainings/guardian_months/2020-08/world/distilroberta"
]
selected_events: [
    "dvc/events/guardian_months/2001-09/world.csv",
    "dvc/events/guardian_months/2008-09/world.csv",
    "dvc/events/guardian_months/2016-06/uk-news.csv",
    "dvc/events/guardian_months/2016-11/us-news.csv",
    "dvc/events/guardian_months/2020-11/us-news.csv",
    "dvc/events/guardian_months/2021-01/us-news.csv",
    "dvc/events/guardian_months/2021-08/world.csv",
    "dvc/events/guardian_months/2022-06/us-news.csv",
    "dvc/events/guardian_months/2022-02/world.csv",
    "dvc/events/guardian_months/2002-12/world.csv",
    "dvc/events/guardian_months/2014-06/world.csv",
    "dvc/events/guardian_months/2020-08/world.csv",
]
processes:
