training_name: tvd8
dataset_base_path: "dvc/datasets/guardian"
evaluation_base_path: "dvc/evaluations/guardian_months"
lda_base_path: "dvc/lda/guardian_months_odd"
model_name: "tvd8"
lda:
  num_topics: 20
  iterations: 83
  passes: 22
  chunksize: 319
selected_events_months:
- [dvc/events/guardian/2000/world.csv, 2000-03]
- [dvc/events/guardian/2000/world.csv, 2000-05]
- [dvc/events/guardian/2000/world.csv, 2000-06]
- [dvc/events/guardian/2000/world.csv, 2000-10]
- [dvc/events/guardian/2001/world.csv, 2001-01]
- [dvc/events/guardian/2001/world.csv, 2001-02]
- [dvc/events/guardian/2001/world.csv, 2001-04]
- [dvc/events/guardian/2001/world.csv, 2001-09]
- [dvc/events/guardian/2001/uk-news.csv, 2001-10]
- [dvc/events/guardian/2001/world.csv, 2001-10]
- [dvc/events/guardian/2002/world.csv, 2002-07]
- [dvc/events/guardian/2002/world.csv, 2002-11]
- [dvc/events/guardian/2002/world.csv, 2002-12]
- [dvc/events/guardian/2007/world.csv, 2007-05]
- [dvc/events/guardian/2007/uk-news.csv, 2007-07]
- [dvc/events/guardian/2007/world.csv, 2007-07]
- [dvc/events/guardian/2007/world.csv, 2007-10]
- [dvc/events/guardian/2008/world.csv, 2008-02]
- [dvc/events/guardian/2008/world.csv, 2008-05]
- [dvc/events/guardian/2008/world.csv, 2008-09]
- [dvc/events/guardian/2008/world.csv, 2008-10]
- [dvc/events/guardian/2010/world.csv, 2010-01]
- [dvc/events/guardian/2010/us-news.csv, 2010-04]
- [dvc/events/guardian/2010/world.csv, 2010-04]
- [dvc/events/guardian/2010/us-news.csv, 2010-08]
- [dvc/events/guardian/2010/world.csv, 2010-08]
- [dvc/events/guardian/2010/world.csv, 2010-10]
- [dvc/events/guardian/2010/us-news.csv, 2010-12]
- [dvc/events/guardian/2010/world.csv, 2010-12]
- [dvc/events/guardian/2011/us-news.csv, 2011-04]
- [dvc/events/guardian/2011/us-news.csv, 2011-05]
- [dvc/events/guardian/2012/uk-news.csv, 2012-04]
- [dvc/events/guardian/2012/us-news.csv, 2012-07]
- [dvc/events/guardian/2012/world.csv, 2012-07]
- [dvc/events/guardian/2012/world.csv, 2012-11]
- [dvc/events/guardian/2014/world.csv, 2014-02]
- [dvc/events/guardian/2014/world.csv, 2014-03]
- [dvc/events/guardian/2014/world.csv, 2014-05]
- [dvc/events/guardian/2014/world.csv, 2014-06]
- [dvc/events/guardian/2014/world.csv, 2014-07]
- [dvc/events/guardian/2015/us-news.csv, 2015-04]
- [dvc/events/guardian/2015/us-news.csv, 2015-06]
- [dvc/events/guardian/2015/uk-news.csv, 2015-09]
- [dvc/events/guardian/2015/us-news.csv, 2015-10]
- [dvc/events/guardian/2016/us-news.csv, 2016-01]
- [dvc/events/guardian/2016/us-news.csv, 2016-03]
- [dvc/events/guardian/2016/uk-news.csv, 2016-06]
- [dvc/events/guardian/2016/us-news.csv, 2016-11]
- [dvc/events/guardian/2019/us-news.csv, 2019-03]
- [dvc/events/guardian/2019/world.csv, 2019-03]
- [dvc/events/guardian/2019/world.csv, 2019-04]
- [dvc/events/guardian/2019/world.csv, 2019-06]
- [dvc/events/guardian/2019/world.csv, 2019-07]
- [dvc/events/guardian/2019/world.csv, 2019-09]
- [dvc/events/guardian/2019/us-news.csv, 2019-10]
- [dvc/events/guardian/2019/world.csv, 2019-11]
- [dvc/events/guardian/2019/uk-news.csv, 2019-12]
- [dvc/events/guardian/2019/us-news.csv, 2019-12]
- [dvc/events/guardian/2020/world.csv, 2020-01]
- [dvc/events/guardian/2020/world.csv, 2020-03]
- [dvc/events/guardian/2020/world.csv, 2020-04]
- [dvc/events/guardian/2020/us-news.csv, 2020-05]
- [dvc/events/guardian/2020/world.csv, 2020-06]
- [dvc/events/guardian/2020/world.csv, 2020-08]
- [dvc/events/guardian/2020/us-news.csv, 2020-09]
- [dvc/events/guardian/2020/world.csv, 2020-09]
- [dvc/events/guardian/2020/us-news.csv, 2020-10]
- [dvc/events/guardian/2020/us-news.csv, 2020-11]
- [dvc/events/guardian/2020/world.csv, 2020-11]
- [dvc/events/guardian/2021/uk-news.csv, 2021-01]
- [dvc/events/guardian/2021/us-news.csv, 2021-01]
- [dvc/events/guardian/2021/world.csv, 2021-02]
- [dvc/events/guardian/2021/us-news.csv, 2021-05]
- [dvc/events/guardian/2021/world.csv, 2021-06]
- [dvc/events/guardian/2021/world.csv, 2021-08]
- [dvc/events/guardian/2021/us-news.csv, 2021-09]
- [dvc/events/guardian/2021/world.csv, 2021-10]
- [dvc/events/guardian/2022/world.csv, 2022-02]
- [dvc/events/guardian/2022/world.csv, 2022-03]
- [dvc/events/guardian/2022/world.csv, 2022-05]
- [dvc/events/guardian/2022/us-news.csv, 2022-06]
- [dvc/events/guardian/2022/world.csv, 2022-07]
- [dvc/events/guardian/2022/us-news.csv, 2022-08]
- [dvc/events/guardian/2022/world.csv, 2022-12]
processes:
tvd_l: 8
force_new_tvd: False
repeat_evaluations: 2