training_name: tvd8
training_base_path: "dvc/datasets/guardian_months"
evaluation_base_path: "dvc/evaluations/guardian_months"
lda_base_path: "dvc/lda/guardian_months"
model_name: "tvd8"
lda:
  num_topics: 20
  iterations: 83
  passes: 22
  chunksize: 319
selected_datasets: [
  "dvc/datasets/guardian/2001/world.pkl",
  "dvc/datasets/guardian/2008/world.pkl",
  "dvc/datasets/guardian/2016/uk-news.pkl",
  "dvc/datasets/guardian/2016/us-news.pkl",
  "dvc/datasets/guardian/2020/us-news.pkl",
  "dvc/datasets/guardian/2021/us-news.pkl",
  "dvc/datasets/guardian/2021/world.pkl",
  "dvc/datasets/guardian/2022/us-news.pkl",
  "dvc/datasets/guardian/2022/world.pkl",
  "dvc/datasets/guardian/2002/world.pkl",
  "dvc/datasets/guardian/2014/world.pkl",
  "dvc/datasets/guardian/2020/world.pkl",
]
selected_events: [
  "dvc/events/guardian_months/2001-09/world.csv",
  "dvc/events/guardian_months/2008-09/world.csv",
  "dvc/events/guardian_months/2016-06/uk-news.csv",
  "dvc/events/guardian_months/2016-11/us-news.csv",
  "dvc/events/guardian_months/2020-11/us-news.csv",
  "dvc/events/guardian_months/2021-01/us-news.csv",
  "dvc/events/guardian_months/2021-08/world.csv",
  "dvc/events/guardian_months/2022-06/us-news.csv",
  "dvc/events/guardian_months/2022-02/world.csv",
  "dvc/events/guardian_months/2002-12/world.csv",
  "dvc/events/guardian_months/2014-06/world.csv",
  "dvc/events/guardian_months/2020-08/world.csv",
]
lda_paths: [
  "dvc/lda/guardian_months/2001/world",
  "dvc/lda/guardian_months/2008/world",
  "dvc/lda/guardian_months/2016/uk-news",
  "dvc/lda/guardian_months/2016/us-news",
  "dvc/lda/guardian_months/2020/us-news",
  "dvc/lda/guardian_months/2021/us-news",
  "dvc/lda/guardian_months/2021/world",
  "dvc/lda/guardian_months/2022/us-news",
  "dvc/lda/guardian_months/2022/world",
  "dvc/lda/guardian_months/2002/world",
  "dvc/lda/guardian_months/2014/world",
  "dvc/lda/guardian_months/2020/world",
]
selected_months: [
    "2001-09",
    "2008-09",
    "2016-06",
    "2016-11",
    "2020-11",
    "2021-01",
    "2021-08",
    "2022-06",
    "2022-02",
    "2002-12",
    "2014-06",
    "2020-08",
]
processes:
tvd_l: 8
force_new_tvd: False
repeat_evaluations: 5