training_name: tvd8
training_base_path: "dvc/datasets/guardian_months"
evaluation_base_path: "dvc/evaluations/guardian_months"
lda_base_path: "dvc/lda/guardian_months"
model_name: "tvd8"
lda:
  num_topics: 20
  iterations: 83
  passes: 22
  chunksize: 319
selected_datasets: [
    "dvc/datasets/guardian/2000-7-1_2002-6-30/world.pkl",
    "dvc/datasets/guardian/2007-7-1_2009-6-30/world.pkl",
    "dvc/datasets/guardian/2015-7-1_2017-6-30/uk-news.pkl",
    "dvc/datasets/guardian/2015-7-1_2017-6-30/us-news.pkl",
    "dvc/datasets/guardian/2019-7-1_2021-6-30/us-news.pkl",
    "dvc/datasets/guardian/2020-7-1_2022-6-30/us-news.pkl",
    "dvc/datasets/guardian/2020-7-1_2022-6-30/world.pkl",
    "dvc/datasets/guardian/2021-7-1_2023-6-30/us-news.pkl",
    "dvc/datasets/guardian/2021-7-1_2023-6-30/world.pkl",
    "dvc/datasets/guardian/1999-7-1_2001-6-30/us-news.pkl",
    "dvc/datasets/guardian/2001-7-1_2003-6-30/world.pkl",
    "dvc/datasets/guardian/2013-7-1_2015-6-30/world.pkl",
    "dvc/datasets/guardian/2019-7-1_2021-6-30/world.pkl",
]
selected_events: [
    "dvc/events/guardian_months/2000-7-1_2002-6-30/world.csv",
    "dvc/events/guardian_months/2007-7-1_2009-6-30/world.csv",
    "dvc/events/guardian_months/2015-7-1_2017-6-30/uk-news.csv",
    "dvc/events/guardian_months/2015-7-1_2017-6-30/us-news.csv",
    "dvc/events/guardian_months/2019-7-1_2021-6-30/us-news.csv",
    "dvc/events/guardian_months/2020-7-1_2022-6-30/us-news.csv",
    "dvc/events/guardian_months/2020-7-1_2022-6-30/world.csv",
    "dvc/events/guardian_months/2021-7-1_2023-6-30/us-news.csv",
    "dvc/events/guardian_months/2021-7-1_2023-6-30/world.csv",
    "dvc/events/guardian_months/1999-7-1_2001-6-30/us-news.csv",
    "dvc/events/guardian_months/2001-7-1_2003-6-30/world.csv",
    "dvc/events/guardian_months/2013-7-1_2015-6-30/world.csv",
    "dvc/events/guardian_months/2019-7-1_2021-6-30/world.csv",
]
lda_paths: [
    "dvc/lda/guardian_months/2000-7-1_2002-6-30/world",
    "dvc/lda/guardian_months/2007-7-1_2009-6-30/world",
    "dvc/lda/guardian_months/2015-7-1_2017-6-30/uk-news",
    "dvc/lda/guardian_months/2015-7-1_2017-6-30/us-news",
    "dvc/lda/guardian_months/2019-7-1_2021-6-30/us-news",
    "dvc/lda/guardian_months/2020-7-1_2022-6-30/us-news",
    "dvc/lda/guardian_months/2020-7-1_2022-6-30/world",
    "dvc/lda/guardian_months/2021-7-1_2023-6-30/us-news",
    "dvc/lda/guardian_months/2021-7-1_2023-6-30/world",
    "dvc/lda/guardian_months/1999-7-1_2001-6-30/us-news",
    "dvc/lda/guardian_months/2001-7-1_2003-6-30/world",
    "dvc/lda/guardian_months/2013-7-1_2015-6-30/world",
    "dvc/lda/guardian_months/2019-7-1_2021-6-30/world",
]
selected_months: [
    "2001-09",
    "2008-09",
    "2016-06",
    "2016-11",
    "2020-11",
    "2021-01",
    "2021-08",
    "2022-06",
    "2022-02",
    "2000-12",
    "2002-12",
    "2014-06",
    "2020-08",
]
processes:
tvd_l: 8
force_new_tvd: False
repeat_evaluations: 5