training_name: confusion_ff_tfidf_l90
dataset_base_path: "dvc/datasets/artificial_split"
evaluation_base_path: "dvc/evaluations/artificial_split"
model_name: "confusion_ff_tfidf_l90"
topn_events: 1
selected_trainings: [
  "dvc/trainings/artificial_split/2000/us-news_uk-news_2000-04-14/confusion_ff_tfidf_l90",
  "dvc/trainings/artificial_split/2010/us-news_world_2010-04-15/confusion_ff_tfidf_l90",
  "dvc/trainings/artificial_split/2015/uk-news_us-news_2015-05-07/confusion_ff_tfidf_l90",
  "dvc/trainings/artificial_split/2019/uk-news_world_2019-01-18/confusion_ff_tfidf_l90",
  "dvc/trainings/artificial_split/2019/uk-news_world_2019-10-30/confusion_ff_tfidf_l90",
  "dvc/trainings/artificial_split/2019/us-news_uk-news_2019-03-27/confusion_ff_tfidf_l90",
  "dvc/trainings/artificial_split/2022/us-news_world_2022-02-16/confusion_ff_tfidf_l90",
  "dvc/trainings/artificial_split/2022/us-news_world_2022-03-17/confusion_ff_tfidf_l90",
]
selected_events: [
  "dvc/events/artificial_split/2000/us-news_uk-news_2000-04-14.csv",
  "dvc/events/artificial_split/2010/us-news_world_2010-04-15.csv",
  "dvc/events/artificial_split/2015/uk-news_us-news_2015-05-07.csv",
  "dvc/events/artificial_split/2019/uk-news_world_2019-01-18.csv",
  "dvc/events/artificial_split/2019/uk-news_world_2019-10-30.csv",
  "dvc/events/artificial_split/2019/us-news_uk-news_2019-03-27.csv",
  "dvc/events/artificial_split/2022/us-news_world_2022-02-16.csv",
  "dvc/events/artificial_split/2022/us-news_world_2022-03-17.csv",
]
lda_paths: [
  "dvc/lda/artificial_split/2000/us-news_uk-news_2000-04-14",
  "dvc/lda/artificial_split/2010/us-news_world_2010-04-15",
  "dvc/lda/artificial_split/2015/uk-news_us-news_2015-05-07",
  "dvc/lda/artificial_split/2019/uk-news_world_2019-01-18",
  "dvc/lda/artificial_split/2019/uk-news_world_2019-10-30",
  "dvc/lda/artificial_split/2019/us-news_uk-news_2019-03-27",
  "dvc/lda/artificial_split/2022/us-news_world_2022-02-16",
  "dvc/lda/artificial_split/2022/us-news_world_2022-03-17",
]
processes:
