name: distilroberta
dtype: float32
train_ratio: 0.8
batch_size: 64
learning_rate: 8.0e-05
min_epochs: 1000
max_epochs: 5000
indicator_accuracy_weighting: true
vectorizer: all-distilroberta-v1
split_distance: 8
datasets:
- dvc/datasets/guardian/2000/us-news.csv
- dvc/datasets/guardian/2000/world.csv
- dvc/datasets/guardian/2001/us-news.csv
- dvc/datasets/guardian/2001/world.csv
- dvc/datasets/guardian/2002/us-news.csv
- dvc/datasets/guardian/2002/world.csv
- dvc/datasets/guardian/2007/uk-news.csv
- dvc/datasets/guardian/2007/us-news.csv
- dvc/datasets/guardian/2007/world.csv
- dvc/datasets/guardian/2008/us-news.csv
- dvc/datasets/guardian/2008/world.csv
- dvc/datasets/guardian/2010/us-news.csv
- dvc/datasets/guardian/2010/world.csv
- dvc/datasets/guardian/2011/world.csv
- dvc/datasets/guardian/2012/uk-news.csv
- dvc/datasets/guardian/2012/us-news.csv
- dvc/datasets/guardian/2012/world.csv
- dvc/datasets/guardian/2014/world.csv
- dvc/datasets/guardian/2015/us-news.csv
- dvc/datasets/guardian/2016/us-news.csv
- dvc/datasets/guardian/2016/world.csv
- dvc/datasets/guardian/2019/us-news.csv
- dvc/datasets/guardian/2019/world.csv
- dvc/datasets/guardian/2020/world.csv
- dvc/datasets/guardian/2021/uk-news.csv
- dvc/datasets/guardian/2021/us-news.csv
- dvc/datasets/guardian/2021/world.csv
- dvc/datasets/guardian/2022/us-news.csv
- dvc/datasets/guardian/2022/world.csv
selected_months:
- 2000-01
- 2000-03
- 2000-05
- 2001-01
- 2001-02
- 2002-01
- 2002-03
- 2002-05
- 2007-01
- 2007-05
- 2008-01
- 2008-02
- 2008-05
- 2010-01
- 2010-04
- 2010-08
- 2011-01
- 2011-02
- 2012-04
- 2012-07
- 2014-02
- 2014-03
- 2015-04
- 2015-06
- 2016-01
- 2016-02
- 2016-03
- 2019-03
- 2020-01
- 2020-03
- 2021-01
- 2021-02
- 2022-02
- 2022-03
- 2022-06
trainings_root: dvc/trainings/guardian_months
overwrite_trainings: new
deterministic: false
