name: "random"
split_distance: 180
datasets: [
    "dvc/datasets/guardian/2000/world.pkl",
    "dvc/datasets/guardian/2001/uk-news.pkl",
    "dvc/datasets/guardian/2001/world.pkl",
    "dvc/datasets/guardian/2002/world.pkl",
    "dvc/datasets/guardian/2007/uk-news.pkl",
    "dvc/datasets/guardian/2007/world.pkl",
    "dvc/datasets/guardian/2008/world.pkl",
    "dvc/datasets/guardian/2010/uk-news.pkl",
    "dvc/datasets/guardian/2010/us-news.pkl",
    "dvc/datasets/guardian/2010/world.pkl",
    "dvc/datasets/guardian/2011/us-news.pkl",
    "dvc/datasets/guardian/2012/uk-news.pkl",
    "dvc/datasets/guardian/2012/us-news.pkl",
    "dvc/datasets/guardian/2012/world.pkl",
    "dvc/datasets/guardian/2014/world.pkl",
    "dvc/datasets/guardian/2015/uk-news.pkl",
    "dvc/datasets/guardian/2015/us-news.pkl",
    "dvc/datasets/guardian/2016/uk-news.pkl",
    "dvc/datasets/guardian/2016/us-news.pkl",
    "dvc/datasets/guardian/2019/uk-news.pkl",
    "dvc/datasets/guardian/2019/us-news.pkl",
    "dvc/datasets/guardian/2019/world.pkl",
    "dvc/datasets/guardian/2020/uk-news.pkl",
    "dvc/datasets/guardian/2020/us-news.pkl",
    "dvc/datasets/guardian/2020/world.pkl",
    "dvc/datasets/guardian/2019/world.pkl",
    "dvc/datasets/guardian/2020/us-news.pkl",
    "dvc/datasets/guardian/2020/world.pkl",
    "dvc/datasets/guardian/2022/us-news.pkl",

  ]
trainings_root: dvc/trainings/guardian
overwrite_trainings: new
deterministic: False
random: True