training_name: distilroberta
dataset_base_path: "dvc/datasets/generated"
evaluation_base_path: "dvc/evaluations/generated"
model_name: "distilroberta"
selected_trainings: [
  "dvc/trainings/generated/2007/world/distilroberta",
  "dvc/trainings/generated/2010/world/distilroberta",
  "dvc/trainings/generated/2012/world/distilroberta",
  "dvc/trainings/generated/2014/world/distilroberta",
  "dvc/trainings/generated/2019/world/distilroberta",
  "dvc/trainings/generated/2020/world/distilroberta",
  "dvc/trainings/generated/2021/world/distilroberta",
  "dvc/trainings/generated/2022/world/distilroberta",
]
selected_events: [
  "dvc/events/generated/2007/world.csv",
  "dvc/events/generated/2010/world.csv",
  "dvc/events/generated/2012/world.csv",
  "dvc/events/generated/2014/world.csv",
  "dvc/events/generated/2019/world.csv",
  "dvc/events/generated/2020/world.csv",
  "dvc/events/generated/2021/world.csv",
  "dvc/events/generated/2022/world.csv",
]
processes:
