training_name: confusion
dataset_base_path: "dvc/datasets/guardian"
training_base_path: "dvc/trainings/guardian"
evaluation_base_path: "dvc/evaluations/guardian"
model_name: "confusion"
topn_events: 5
selected_trainings: [
  "dvc/trainings/guardian/2000/world/confusion",
  "dvc/trainings/guardian/2001/world/confusion",
  "dvc/trainings/guardian/2001/uk-news/confusion",
  "dvc/trainings/guardian/2001/world/confusion",
  "dvc/trainings/guardian/2002/world/confusion",
  "dvc/trainings/guardian/2007/uk-news/confusion",
  "dvc/trainings/guardian/2007/world/confusion",
  "dvc/trainings/guardian/2008/world/confusion",
  "dvc/trainings/guardian/2010/us-news/confusion",
  "dvc/trainings/guardian/2010/world/confusion",
  "dvc/trainings/guardian/2011/us-news/confusion",
  "dvc/trainings/guardian/2012/uk-news/confusion",
  "dvc/trainings/guardian/2012/world/confusion",
  "dvc/trainings/guardian/2014/world/confusion",
  "dvc/trainings/guardian/2015/uk-news/confusion",
  "dvc/trainings/guardian/2015/us-news/confusion",
  "dvc/trainings/guardian/2016/uk-news/confusion",
  "dvc/trainings/guardian/2016/us-news/confusion",
  "dvc/trainings/guardian/2019/uk-news/confusion",
  "dvc/trainings/guardian/2019/us-news/confusion",
  "dvc/trainings/guardian/2019/world/confusion",
  "dvc/trainings/guardian/2020/us-news/confusion",
  "dvc/trainings/guardian/2020/world/confusion",
  "dvc/trainings/guardian/2021/us-news/confusion",
  "dvc/trainings/guardian/2021/world/confusion",
  "dvc/trainings/guardian/2022/world/confusion",
  "dvc/trainings/guardian/2022/us-news/confusion",
]
selected_events: [
  "dvc/events/onthisday/2000/world.csv",
  "dvc/events/onthisday/2001/world.csv",
  "dvc/events/onthisday/2001/uk-news.csv",
  "dvc/events/onthisday/2001/world.csv",
  "dvc/events/onthisday/2002/world.csv",
  "dvc/events/onthisday/2007/uk-news.csv",
  "dvc/events/onthisday/2007/world.csv",
  "dvc/events/onthisday/2008/world.csv",
  "dvc/events/onthisday/2010/us-news.csv",
  "dvc/events/onthisday/2010/world.csv",
  "dvc/events/onthisday/2011/us-news.csv",
  "dvc/events/onthisday/2012/uk-news.csv",
  "dvc/events/onthisday/2012/world.csv",
  "dvc/events/onthisday/2014/world.csv",
  "dvc/events/onthisday/2015/uk-news.csv",
  "dvc/events/onthisday/2015/us-news.csv",
  "dvc/events/onthisday/2016/uk-news.csv",
  "dvc/events/onthisday/2016/us-news.csv",
  "dvc/events/onthisday/2019/uk-news.csv",
  "dvc/events/onthisday/2019/us-news.csv",
  "dvc/events/onthisday/2019/world.csv",
  "dvc/events/onthisday/2020/us-news.csv",
  "dvc/events/onthisday/2020/world.csv",
  "dvc/events/onthisday/2021/us-news.csv",
  "dvc/events/onthisday/2021/world.csv",
  "dvc/events/onthisday/2022/world.csv",
  "dvc/events/onthisday/2022/us-news.csv",
]
processes:
