training_name: distilroberta
dataset_base_path: "dvc/datasets/guardian"
training_base_path: "dvc/trainings/guardian"
evaluation_base_path: "dvc/evaluations/guardian"
model_name: "distilroberta"
topn_events: 5
selected_trainings: [
  "dvc/trainings/guardian/2000/world/distilroberta",
  "dvc/trainings/guardian/2001/world/distilroberta",
  "dvc/trainings/guardian/2001/uk-news/distilroberta",
  "dvc/trainings/guardian/2001/world/distilroberta",
  "dvc/trainings/guardian/2002/world/distilroberta",
  "dvc/trainings/guardian/2007/uk-news/distilroberta",
  "dvc/trainings/guardian/2007/world/distilroberta",
  "dvc/trainings/guardian/2008/world/distilroberta",
  "dvc/trainings/guardian/2010/us-news/distilroberta",
  "dvc/trainings/guardian/2010/world/distilroberta",
  "dvc/trainings/guardian/2011/us-news/distilroberta",
  "dvc/trainings/guardian/2012/uk-news/distilroberta",
  "dvc/trainings/guardian/2012/world/distilroberta",
  "dvc/trainings/guardian/2014/world/distilroberta",
  "dvc/trainings/guardian/2015/uk-news/distilroberta",
  "dvc/trainings/guardian/2015/us-news/distilroberta",
  "dvc/trainings/guardian/2016/uk-news/distilroberta",
  "dvc/trainings/guardian/2016/us-news/distilroberta",
  "dvc/trainings/guardian/2019/uk-news/distilroberta",
  "dvc/trainings/guardian/2019/us-news/distilroberta",
  "dvc/trainings/guardian/2019/world/distilroberta",
  "dvc/trainings/guardian/2020/us-news/distilroberta",
  "dvc/trainings/guardian/2020/world/distilroberta",
  "dvc/trainings/guardian/2021/us-news/distilroberta",
  "dvc/trainings/guardian/2021/world/distilroberta",
  "dvc/trainings/guardian/2022/world/distilroberta",
  "dvc/trainings/guardian/2022/us-news/distilroberta",
]
selected_events: [
  "dvc/events/guardian/2000/world.csv",
  "dvc/events/guardian/2001/world.csv",
  "dvc/events/guardian/2001/uk-news.csv",
  "dvc/events/guardian/2001/world.csv",
  "dvc/events/guardian/2002/world.csv",
  "dvc/events/guardian/2007/uk-news.csv",
  "dvc/events/guardian/2007/world.csv",
  "dvc/events/guardian/2008/world.csv",
  "dvc/events/guardian/2010/us-news.csv",
  "dvc/events/guardian/2010/world.csv",
  "dvc/events/guardian/2011/us-news.csv",
  "dvc/events/guardian/2012/uk-news.csv",
  "dvc/events/guardian/2012/world.csv",
  "dvc/events/guardian/2014/world.csv",
  "dvc/events/guardian/2015/uk-news.csv",
  "dvc/events/guardian/2015/us-news.csv",
  "dvc/events/guardian/2016/uk-news.csv",
  "dvc/events/guardian/2016/us-news.csv",
  "dvc/events/guardian/2019/uk-news.csv",
  "dvc/events/guardian/2019/us-news.csv",
  "dvc/events/guardian/2019/world.csv",
  "dvc/events/guardian/2020/us-news.csv",
  "dvc/events/guardian/2020/world.csv",
  "dvc/events/guardian/2021/us-news.csv",
  "dvc/events/guardian/2021/world.csv",
  "dvc/events/guardian/2022/world.csv",
  "dvc/events/guardian/2022/us-news.csv",
]
processes:
