training_name: random
dataset_base_path: "dvc/datasets/guardian"
training_base_path: "dvc/datasets/guardian"
evaluation_base_path: "dvc/evaluations/guardian"
model_name: "random"
selected_trainings: [
  "dvc/trainings/guardian/1999-7-1_2001-6-30/world/random",
  "dvc/trainings/guardian/2000-7-1_2002-6-30/world/random",
  "dvc/trainings/guardian/2000-7-1_2002-6-30/uk-news/random",
  "dvc/trainings/guardian/2000-7-1_2002-6-30/world/random",
  "dvc/trainings/guardian/2001-7-1_2003-6-30/world/random",
  "dvc/trainings/guardian/2006-7-1_2008-6-30/uk-news/random",
  "dvc/trainings/guardian/2006-7-1_2008-6-30/world/random",
  "dvc/trainings/guardian/2007-7-1_2009-6-30/world/random",
  "dvc/trainings/guardian/2009-7-1_2011-6-30/us-news/random",
  "dvc/trainings/guardian/2009-7-1_2011-6-30/world/random",
  "dvc/trainings/guardian/2010-7-1_2012-6-30/us-news/random",
  "dvc/trainings/guardian/2011-7-1_2013-6-30/uk-news/random",
  "dvc/trainings/guardian/2011-7-1_2013-6-30/world/random",
  "dvc/trainings/guardian/2013-7-1_2015-6-30/world/random",
  "dvc/trainings/guardian/2014-7-1_2016-6-30/uk-news/random",
  "dvc/trainings/guardian/2014-7-1_2016-6-30/us-news/random",
  "dvc/trainings/guardian/2015-7-1_2017-6-30/uk-news/random",
  "dvc/trainings/guardian/2015-7-1_2017-6-30/us-news/random",
  "dvc/trainings/guardian/2018-7-1_2020-6-30/uk-news/random",
  "dvc/trainings/guardian/2018-7-1_2020-6-30/us-news/random",
  "dvc/trainings/guardian/2018-7-1_2020-6-30/world/random",
  "dvc/trainings/guardian/2019-7-1_2021-6-30/us-news/random",
  "dvc/trainings/guardian/2019-7-1_2021-6-30/world/random",
  "dvc/trainings/guardian/2020-7-1_2022-6-30/us-news/random",
  "dvc/trainings/guardian/2020-7-1_2022-6-30/world/random",
  "dvc/trainings/guardian/2021-7-1_2023-6-30/world/random",
  "dvc/trainings/guardian/2021-7-1_2023-6-30/us-news/random",
]
selected_events: [
  "dvc/events/guardian/1999-7-1_2001-6-30/world.csv",
  "dvc/events/guardian/2000-7-1_2002-6-30/world.csv",
  "dvc/events/guardian/2000-7-1_2002-6-30/uk-news.csv",
  "dvc/events/guardian/2000-7-1_2002-6-30/world.csv",
  "dvc/events/guardian/2001-7-1_2003-6-30/world.csv",
  "dvc/events/guardian/2006-7-1_2008-6-30/uk-news.csv",
  "dvc/events/guardian/2006-7-1_2008-6-30/world.csv",
  "dvc/events/guardian/2007-7-1_2009-6-30/world.csv",
  "dvc/events/guardian/2009-7-1_2011-6-30/us-news.csv",
  "dvc/events/guardian/2009-7-1_2011-6-30/world.csv",
  "dvc/events/guardian/2010-7-1_2012-6-30/us-news.csv",
  "dvc/events/guardian/2011-7-1_2013-6-30/uk-news.csv",
  "dvc/events/guardian/2011-7-1_2013-6-30/world.csv",
  "dvc/events/guardian/2013-7-1_2015-6-30/world.csv",
  "dvc/events/guardian/2014-7-1_2016-6-30/uk-news.csv",
  "dvc/events/guardian/2014-7-1_2016-6-30/us-news.csv",
  "dvc/events/guardian/2015-7-1_2017-6-30/uk-news.csv",
  "dvc/events/guardian/2015-7-1_2017-6-30/us-news.csv",
  "dvc/events/guardian/2018-7-1_2020-6-30/uk-news.csv",
  "dvc/events/guardian/2018-7-1_2020-6-30/us-news.csv",
  "dvc/events/guardian/2018-7-1_2020-6-30/world.csv",
  "dvc/events/guardian/2019-7-1_2021-6-30/us-news.csv",
  "dvc/events/guardian/2019-7-1_2021-6-30/world.csv",
  "dvc/events/guardian/2020-7-1_2022-6-30/us-news.csv",
  "dvc/events/guardian/2020-7-1_2022-6-30/world.csv",
  "dvc/events/guardian/2021-7-1_2023-6-30/world.csv",
  "dvc/events/guardian/2021-7-1_2023-6-30/us-news.csv",
]
processes:
