name: "distilroberta"
dtype: "float32"
train_ratio: 0.8
batch_size: 64
learning_rate: 8e-05
min_epochs: 1000
max_epochs: 5000
indicator_accuracy_weighting: True
first_split_idx: 2
vectorizer: "all-distilroberta-v1"
split_distance: 8
datasets: [
    "dvc/datasets/generated/2001/world.pkl",
    "dvc/datasets/generated/2007/world.pkl",
    "dvc/datasets/generated/2010/world.pkl",
    "dvc/datasets/generated/2012/world.pkl",
    "dvc/datasets/generated/2014/world.pkl",
    "dvc/datasets/generated/2016/world.pkl",
    "dvc/datasets/generated/2019/world.pkl",
    "dvc/datasets/generated/2020/world.pkl",
    "dvc/datasets/generated/2021/world.pkl",
    "dvc/datasets/generated/2022/world.pkl"
  ]
trainings_root: dvc/trainings/generated
overwrite_trainings: new
deterministic: False