name: "random"
first_split_idx: 15
datasets: [
    "dvc/datasets/generated/2001/world.csv",
    "dvc/datasets/generated/2007/world.csv",
    "dvc/datasets/generated/2010/world.csv",
    "dvc/datasets/generated/2012/world.csv",
    "dvc/datasets/generated/2014/world.csv",
    "dvc/datasets/generated/2016/world.csv",
    "dvc/datasets/generated/2019/world.csv",
    "dvc/datasets/generated/2020/world.csv",
    "dvc/datasets/generated/2021/world.csv",
    "dvc/datasets/generated/2022/world.csv"
  ]
trainings_root: dvc/trainings/generated
overwrite_trainings: new
deterministic: False
monthly: true