training:
  name: "distilroberta1"
  dtype: "float32"
  train_ratio: 0.8
  batch_size: 64
  learning_rate: 8e-05
  min_epochs: 1000
  max_epochs: 5000
  indicator_accuracy_weighting: True
  vectorizer:
    type: llm
    tfidf:
      preprocess_texts: True
    llm:
      model_name: "all-distilroberta-v1"
  training_scheme: "confusion"
  model_type: "simple"
  confusion:
    split_distance: 8
  llm:
    freeze_backend: True
datasets: [
    "dvc/datasets/guardian_extended/1999-7-1_2001-6-30/world.pkl",
    "dvc/datasets/guardian_extended/1999-7-1_2001-6-30/world.pkl",
    "dvc/datasets/guardian_extended/1999-7-1_2001-6-30/world.pkl",

    "dvc/datasets/guardian_extended/2000-7-1_2002-6-30/uk-news.pkl",

    "dvc/datasets/guardian_extended/2000-7-1_2002-6-30/world.pkl",
    "dvc/datasets/guardian_extended/2000-7-1_2002-6-30/world.pkl",
    "dvc/datasets/guardian_extended/2000-7-1_2002-6-30/world.pkl",
    "dvc/datasets/guardian_extended/2000-7-1_2002-6-30/world.pkl",

    "dvc/datasets/guardian_extended/2001-7-1_2003-6-30/world.pkl",
    "dvc/datasets/guardian_extended/2001-7-1_2003-6-30/world.pkl",
    "dvc/datasets/guardian_extended/2001-7-1_2003-6-30/world.pkl",

    "dvc/datasets/guardian_extended/2006-7-1_2008-6-30/uk-news.pkl",
    "dvc/datasets/guardian_extended/2006-7-1_2008-6-30/uk-news.pkl",

    "dvc/datasets/guardian_extended/2006-7-1_2008-6-30/world.pkl",

    "dvc/datasets/guardian_extended/2007-7-1_2009-6-30/world.pkl",
    "dvc/datasets/guardian_extended/2007-7-1_2009-6-30/world.pkl",
    "dvc/datasets/guardian_extended/2007-7-1_2009-6-30/world.pkl",
    "dvc/datasets/guardian_extended/2007-7-1_2009-6-30/world.pkl",

    "dvc/datasets/guardian_extended/2009-7-1_2011-6-30/us-news.pkl",
    "dvc/datasets/guardian_extended/2009-7-1_2011-6-30/us-news.pkl",
    "dvc/datasets/guardian_extended/2009-7-1_2011-6-30/us-news.pkl",

    "dvc/datasets/guardian_extended/2009-7-1_2011-6-30/world.pkl",
    "dvc/datasets/guardian_extended/2009-7-1_2011-6-30/world.pkl",

    "dvc/datasets/guardian_extended/2010-7-1_2012-6-30/us-news.pkl",

    "dvc/datasets/guardian_extended/2011-7-1_2013-6-30/us-news.pkl",

    "dvc/datasets/guardian_extended/2011-7-1_2013-6-30/world.pkl",
    "dvc/datasets/guardian_extended/2011-7-1_2013-6-30/world.pkl",
    "dvc/datasets/guardian_extended/2011-7-1_2013-6-30/world.pkl",

    "dvc/datasets/guardian_extended/2013-7-1_2015-6-30/world.pkl",
    "dvc/datasets/guardian_extended/2013-7-1_2015-6-30/world.pkl",
    "dvc/datasets/guardian_extended/2013-7-1_2015-6-30/world.pkl",
    "dvc/datasets/guardian_extended/2013-7-1_2015-6-30/world.pkl",
    "dvc/datasets/guardian_extended/2013-7-1_2015-6-30/world.pkl",

    "dvc/datasets/guardian_extended/2014-7-1_2016-6-30/uk-news.pkl",

    "dvc/datasets/guardian_extended/2014-7-1_2016-6-30/us-news.pkl",
    "dvc/datasets/guardian_extended/2014-7-1_2016-6-30/us-news.pkl",
    "dvc/datasets/guardian_extended/2014-7-1_2016-6-30/us-news.pkl",

    "dvc/datasets/guardian_extended/2015-7-1_2017-6-30/uk-news.pkl",

    "dvc/datasets/guardian_extended/2015-7-1_2017-6-30/us-news.pkl",
    "dvc/datasets/guardian_extended/2015-7-1_2017-6-30/us-news.pkl",

    "dvc/datasets/guardian_extended/2018-7-1_2020-6-30/uk-news.pkl",

    "dvc/datasets/guardian_extended/2018-7-1_2020-6-30/us-news.pkl",
    "dvc/datasets/guardian_extended/2018-7-1_2020-6-30/us-news.pkl",
    "dvc/datasets/guardian_extended/2018-7-1_2020-6-30/us-news.pkl",

    "dvc/datasets/guardian_extended/2018-7-1_2020-6-30/world.pkl",
    "dvc/datasets/guardian_extended/2018-7-1_2020-6-30/world.pkl",
    "dvc/datasets/guardian_extended/2018-7-1_2020-6-30/world.pkl",
    "dvc/datasets/guardian_extended/2018-7-1_2020-6-30/world.pkl",
    "dvc/datasets/guardian_extended/2018-7-1_2020-6-30/world.pkl",
    "dvc/datasets/guardian_extended/2018-7-1_2020-6-30/world.pkl",

    "dvc/datasets/guardian_extended/2019-7-1_2021-6-30/us-news.pkl",
    "dvc/datasets/guardian_extended/2019-7-1_2021-6-30/us-news.pkl",
    "dvc/datasets/guardian_extended/2019-7-1_2021-6-30/us-news.pkl",
    "dvc/datasets/guardian_extended/2019-7-1_2021-6-30/us-news.pkl",
    "dvc/datasets/guardian_extended/2019-7-1_2021-6-30/us-news.pkl",

    "dvc/datasets/guardian_extended/2019-7-1_2021-6-30/world.pkl",
    "dvc/datasets/guardian_extended/2019-7-1_2021-6-30/world.pkl",
    "dvc/datasets/guardian_extended/2019-7-1_2021-6-30/world.pkl",
    "dvc/datasets/guardian_extended/2019-7-1_2021-6-30/world.pkl",
    "dvc/datasets/guardian_extended/2019-7-1_2021-6-30/world.pkl",
    "dvc/datasets/guardian_extended/2019-7-1_2021-6-30/world.pkl",

    "dvc/datasets/guardian_extended/2020-7-1_2022-6-30/uk-news.pkl",

    "dvc/datasets/guardian_extended/2020-7-1_2022-6-30/us-news.pkl",
    "dvc/datasets/guardian_extended/2020-7-1_2022-6-30/us-news.pkl",
    "dvc/datasets/guardian_extended/2020-7-1_2022-6-30/us-news.pkl",

    "dvc/datasets/guardian_extended/2020-7-1_2022-6-30/world.pkl",
    "dvc/datasets/guardian_extended/2020-7-1_2022-6-30/world.pkl",
    "dvc/datasets/guardian_extended/2020-7-1_2022-6-30/world.pkl",
    "dvc/datasets/guardian_extended/2020-7-1_2022-6-30/world.pkl",

    "dvc/datasets/guardian_extended/2021-7-1_2023-6-30/us-news.pkl",
    "dvc/datasets/guardian_extended/2021-7-1_2023-6-30/us-news.pkl",

    "dvc/datasets/guardian_extended/2021-7-1_2023-6-30/world.pkl",
    "dvc/datasets/guardian_extended/2021-7-1_2023-6-30/world.pkl",
    "dvc/datasets/guardian_extended/2021-7-1_2023-6-30/world.pkl",
]
selected_months: [
    "2000-05",
    "2000-06",
    "2000-10",

    "2001-10",

    "2001-01",
    "2001-02",
    "2001-04",
    "2001-09",

    "2002-07",
    "2002-11",
    "2002-12",

    "2007-05",
    "2007-07",

    "2007-10",

    "2008-02",
    "2008-05",
    "2008-09",
    "2008-10",

    "2010-04",
    "2010-08",
    "2010-12",

    "2010-01",
    "2010-10",

    "2011-05",

    "2012-07",

    "2012-04",
    "2012-07",
    "2012-11",

    "2014-02",
    "2014-03",
    "2014-05",
    "2014-06",
    "2014-07",

    "2015-09",

    "2015-04",
    "2015-06",
    "2015-10",

    "2016-06",

    "2016-03",
    "2016-11",

    "2019-12",

    "2019-03",
    "2019-10",
    "2019-12",

    "2019-03",
    "2019-04",
    "2019-06",
    "2019-07",
    "2019-09",
    "2019-12",

    "2020-04",
    "2020-05",
    "2020-09",
    "2020-10",
    "2020-11",

    "2020-01",
    "2020-03",
    "2020-06",
    "2020-08",
    "2020-09",
    "2020-11",

    "2021-01",

    "2021-01",
    "2021-05",
    "2021-09",

    "2021-02",
    "2021-06",
    "2021-08",
    "2021-10",

    "2022-06",
    "2022-08",

    "2022-02",
    "2022-03",
    "2022-12",
]
general:
  trainings_root: dvc/trainings/guardian_months
overwrite_trainings: new
deterministic: False
parallel_trainings: 5
