training:
  name: "distilroberta1"
  dtype: "float32"
  train_ratio: 0.8
  batch_size: 64
  learning_rate: 8e-05
  min_epochs: 1000
  max_epochs: 5000
  indicator_accuracy_weighting: True
  vectorizer:
    type: llm
    tfidf:
      preprocess_texts: True
    llm:
      model_name: "all-distilroberta-v1"
  training_scheme: "confusion"
  model_type: "simple"
  confusion:
    split_distance: 8
  llm:
    freeze_backend: True
datasets: [
    "dvc/datasets/guardian_extended/2021-7-1_2023-6-30/us-news.pkl",
    "dvc/datasets/guardian_extended/2021-7-1_2023-6-30/us-news.pkl",

    "dvc/datasets/guardian_extended/2021-7-1_2023-6-30/world.pkl",
    "dvc/datasets/guardian_extended/2021-7-1_2023-6-30/world.pkl",
    "dvc/datasets/guardian_extended/2021-7-1_2023-6-30/world.pkl",
]
selected_months: [
    "2022-06",
    "2022-08",

    "2022-02",
    "2022-03",
    "2022-12",
]
general:
  trainings_root: dvc/trainings/guardian_months
overwrite_trainings: new
deterministic: False
parallel_trainings: 5
