name: distilroberta
dtype: float32
train_ratio: 0.8
batch_size: 64
learning_rate: 8.0e-05
min_epochs: 1000
max_epochs: 5000
indicator_accuracy_weighting: true
vectorizer: all-distilroberta-v1
split_distance: 8
datasets:
- dvc/datasets/guardian/2000/world.csv
- dvc/datasets/guardian/2000/world.csv
- dvc/datasets/guardian/2000/world.csv
- dvc/datasets/guardian/2000/world.csv
- dvc/datasets/guardian/2001/world.csv
- dvc/datasets/guardian/2001/world.csv
- dvc/datasets/guardian/2001/world.csv
- dvc/datasets/guardian/2001/world.csv
- dvc/datasets/guardian/2001/uk-news.csv
- dvc/datasets/guardian/2001/world.csv
- dvc/datasets/guardian/2002/world.csv
- dvc/datasets/guardian/2002/world.csv
- dvc/datasets/guardian/2002/world.csv
- dvc/datasets/guardian/2007/world.csv
- dvc/datasets/guardian/2007/uk-news.csv
- dvc/datasets/guardian/2007/world.csv
- dvc/datasets/guardian/2007/world.csv
- dvc/datasets/guardian/2008/world.csv
- dvc/datasets/guardian/2008/world.csv
- dvc/datasets/guardian/2008/world.csv
- dvc/datasets/guardian/2008/world.csv
- dvc/datasets/guardian/2010/world.csv
- dvc/datasets/guardian/2010/us-news.csv
- dvc/datasets/guardian/2010/world.csv
- dvc/datasets/guardian/2010/us-news.csv
- dvc/datasets/guardian/2010/world.csv
- dvc/datasets/guardian/2010/world.csv
- dvc/datasets/guardian/2010/us-news.csv
- dvc/datasets/guardian/2010/world.csv
- dvc/datasets/guardian/2011/us-news.csv
- dvc/datasets/guardian/2011/us-news.csv
- dvc/datasets/guardian/2012/uk-news.csv
- dvc/datasets/guardian/2012/us-news.csv
- dvc/datasets/guardian/2012/world.csv
- dvc/datasets/guardian/2012/world.csv
- dvc/datasets/guardian/2014/world.csv
- dvc/datasets/guardian/2014/world.csv
- dvc/datasets/guardian/2014/world.csv
- dvc/datasets/guardian/2014/world.csv
- dvc/datasets/guardian/2014/world.csv
- dvc/datasets/guardian/2015/us-news.csv
- dvc/datasets/guardian/2015/us-news.csv
- dvc/datasets/guardian/2015/uk-news.csv
- dvc/datasets/guardian/2015/us-news.csv
- dvc/datasets/guardian/2016/us-news.csv
- dvc/datasets/guardian/2016/us-news.csv
- dvc/datasets/guardian/2016/uk-news.csv
- dvc/datasets/guardian/2016/us-news.csv
- dvc/datasets/guardian/2019/us-news.csv
- dvc/datasets/guardian/2019/world.csv
- dvc/datasets/guardian/2019/world.csv
- dvc/datasets/guardian/2019/world.csv
- dvc/datasets/guardian/2019/world.csv
- dvc/datasets/guardian/2019/world.csv
- dvc/datasets/guardian/2019/us-news.csv
- dvc/datasets/guardian/2019/world.csv
- dvc/datasets/guardian/2019/uk-news.csv
- dvc/datasets/guardian/2019/us-news.csv
- dvc/datasets/guardian/2020/world.csv
- dvc/datasets/guardian/2020/world.csv
- dvc/datasets/guardian/2020/world.csv
- dvc/datasets/guardian/2020/us-news.csv
- dvc/datasets/guardian/2020/world.csv
- dvc/datasets/guardian/2020/world.csv
- dvc/datasets/guardian/2020/us-news.csv
- dvc/datasets/guardian/2020/world.csv
- dvc/datasets/guardian/2020/us-news.csv
- dvc/datasets/guardian/2020/us-news.csv
- dvc/datasets/guardian/2020/world.csv
- dvc/datasets/guardian/2021/uk-news.csv
- dvc/datasets/guardian/2021/us-news.csv
- dvc/datasets/guardian/2021/world.csv
- dvc/datasets/guardian/2021/us-news.csv
- dvc/datasets/guardian/2021/world.csv
- dvc/datasets/guardian/2021/world.csv
- dvc/datasets/guardian/2021/us-news.csv
- dvc/datasets/guardian/2021/world.csv
- dvc/datasets/guardian/2022/world.csv
- dvc/datasets/guardian/2022/world.csv
- dvc/datasets/guardian/2022/world.csv
- dvc/datasets/guardian/2022/us-news.csv
- dvc/datasets/guardian/2022/world.csv
- dvc/datasets/guardian/2022/us-news.csv
- dvc/datasets/guardian/2022/world.csv
selected_months:
- 2000-03
- 2000-05
- 2000-06
- 2000-10
- 2001-01
- 2001-02
- 2001-04
- 2001-09
- 2001-10
- 2001-10
- 2002-07
- 2002-11
- 2002-12
- 2007-05
- 2007-07
- 2007-07
- 2007-10
- 2008-02
- 2008-05
- 2008-09
- 2008-10
- 2010-01
- 2010-04
- 2010-04
- 2010-08
- 2010-08
- 2010-10
- 2010-12
- 2010-12
- 2011-04
- 2011-05
- 2012-04
- 2012-07
- 2012-07
- 2012-11
- 2014-02
- 2014-03
- 2014-05
- 2014-06
- 2014-07
- 2015-04
- 2015-06
- 2015-09
- 2015-10
- 2016-01
- 2016-03
- 2016-06
- 2016-11
- 2019-03
- 2019-03
- 2019-04
- 2019-06
- 2019-07
- 2019-09
- 2019-10
- 2019-11
- 2019-12
- 2019-12
- 2020-01
- 2020-03
- 2020-04
- 2020-05
- 2020-06
- 2020-08
- 2020-09
- 2020-09
- 2020-10
- 2020-11
- 2020-11
- 2021-01
- 2021-01
- 2021-02
- 2021-05
- 2021-06
- 2021-08
- 2021-09
- 2021-10
- 2022-02
- 2022-03
- 2022-05
- 2022-06
- 2022-07
- 2022-08
- 2022-12
trainings_root: dvc/trainings/guardian_months
overwrite_trainings: skip
deterministic: false
