training_name: confusion_ff_tfidf_l180
dataset_base_path: "dvc/datasets/guardian_extended"
training_base_path: "dvc/trainings/guardian_extended"
evaluation_base_path: "dvc/evaluations/guardian_extended"
lda_base_path: "dvc/lda/guardian_extended"
model_name: "confusion_ff_tfidf_l180"
topn_events: 5
selected_trainings: [
  "dvc/trainings/guardian_extended/1999-7-1_2001-6-30/us-news/confusion_ff_tfidf_l180",
  "dvc/trainings/guardian_extended/1999-7-1_2001-6-30/world/confusion_ff_tfidf_l180",
  "dvc/trainings/guardian_extended/2000-7-1_2002-6-30/world/confusion_ff_tfidf_l180",
  "dvc/trainings/guardian_extended/2000-7-1_2002-6-30/uk-news/confusion_ff_tfidf_l180",
  "dvc/trainings/guardian_extended/2000-7-1_2002-6-30/us-news/confusion_ff_tfidf_l180",
  "dvc/trainings/guardian_extended/2000-7-1_2002-6-30/world/confusion_ff_tfidf_l180",
  "dvc/trainings/guardian_extended/2001-7-1_2003-6-30/world/confusion_ff_tfidf_l180",
  "dvc/trainings/guardian_extended/2006-7-1_2008-6-30/uk-news/confusion_ff_tfidf_l180",
  "dvc/trainings/guardian_extended/2006-7-1_2008-6-30/us-news/confusion_ff_tfidf_l180",
  "dvc/trainings/guardian_extended/2006-7-1_2008-6-30/world/confusion_ff_tfidf_l180",
  "dvc/trainings/guardian_extended/2007-7-1_2009-6-30/world/confusion_ff_tfidf_l180",
  "dvc/trainings/guardian_extended/2009-7-1_2011-6-30/uk-news/confusion_ff_tfidf_l180",
  "dvc/trainings/guardian_extended/2009-7-1_2011-6-30/us-news/confusion_ff_tfidf_l180",
  "dvc/trainings/guardian_extended/2009-7-1_2011-6-30/world/confusion_ff_tfidf_l180",
  "dvc/trainings/guardian_extended/2010-7-1_2012-6-30/us-news/confusion_ff_tfidf_l180",
  "dvc/trainings/guardian_extended/2011-7-1_2013-6-30/uk-news/confusion_ff_tfidf_l180",
  "dvc/trainings/guardian_extended/2011-7-1_2013-6-30/us-news/confusion_ff_tfidf_l180",
  "dvc/trainings/guardian_extended/2011-7-1_2013-6-30/world/confusion_ff_tfidf_l180",
  "dvc/trainings/guardian_extended/2013-7-1_2015-6-30/world/confusion_ff_tfidf_l180",
  "dvc/trainings/guardian_extended/2014-7-1_2016-6-30/uk-news/confusion_ff_tfidf_l180",
  "dvc/trainings/guardian_extended/2014-7-1_2016-6-30/us-news/confusion_ff_tfidf_l180",
  "dvc/trainings/guardian_extended/2015-7-1_2017-6-30/uk-news/confusion_ff_tfidf_l180",
  "dvc/trainings/guardian_extended/2015-7-1_2017-6-30/us-news/confusion_ff_tfidf_l180",
  "dvc/trainings/guardian_extended/2018-7-1_2020-6-30/uk-news/confusion_ff_tfidf_l180",
  "dvc/trainings/guardian_extended/2018-7-1_2020-6-30/us-news/confusion_ff_tfidf_l180",
  "dvc/trainings/guardian_extended/2018-7-1_2020-6-30/world/confusion_ff_tfidf_l180",
  "dvc/trainings/guardian_extended/2019-7-1_2021-6-30/uk-news/confusion_ff_tfidf_l180",
  "dvc/trainings/guardian_extended/2019-7-1_2021-6-30/us-news/confusion_ff_tfidf_l180",
  "dvc/trainings/guardian_extended/2020-7-1_2022-6-30/uk-news/confusion_ff_tfidf_l180",
  "dvc/trainings/guardian_extended/2019-7-1_2021-6-30/world/confusion_ff_tfidf_l180",
  "dvc/trainings/guardian_extended/2020-7-1_2022-6-30/us-news/confusion_ff_tfidf_l180",
  "dvc/trainings/guardian_extended/2020-7-1_2022-6-30/world/confusion_ff_tfidf_l180",
  #"dvc/trainings/guardian_extended/2021-7-1_2023-6-30/uk-news/confusion_ff_tfidf_l180",
  "dvc/trainings/guardian_extended/2021-7-1_2023-6-30/world/confusion_ff_tfidf_l180",
  "dvc/trainings/guardian_extended/2021-7-1_2023-6-30/us-news/confusion_ff_tfidf_l180",
]
selected_events: [
  "dvc/events/guardian_extended/1999-7-1_2001-6-30/us-news.csv",
  "dvc/events/guardian_extended/1999-7-1_2001-6-30/world.csv",
  "dvc/events/guardian_extended/2000-7-1_2002-6-30/world.csv",
  "dvc/events/guardian_extended/2000-7-1_2002-6-30/uk-news.csv",
  "dvc/events/guardian_extended/2000-7-1_2002-6-30/us-news.csv",
  "dvc/events/guardian_extended/2000-7-1_2002-6-30/world.csv",
  "dvc/events/guardian_extended/2001-7-1_2003-6-30/world.csv",
  "dvc/events/guardian_extended/2006-7-1_2008-6-30/uk-news.csv",
  "dvc/events/guardian_extended/2006-7-1_2008-6-30/us-news.csv",
  "dvc/events/guardian_extended/2006-7-1_2008-6-30/world.csv",
  "dvc/events/guardian_extended/2007-7-1_2009-6-30/world.csv",
  "dvc/events/guardian_extended/2009-7-1_2011-6-30/uk-news.csv",
  "dvc/events/guardian_extended/2009-7-1_2011-6-30/us-news.csv",
  "dvc/events/guardian_extended/2009-7-1_2011-6-30/world.csv",
  "dvc/events/guardian_extended/2010-7-1_2012-6-30/us-news.csv",
  "dvc/events/guardian_extended/2011-7-1_2013-6-30/uk-news.csv",
  "dvc/events/guardian_extended/2011-7-1_2013-6-30/us-news.csv",
  "dvc/events/guardian_extended/2011-7-1_2013-6-30/world.csv",
  "dvc/events/guardian_extended/2013-7-1_2015-6-30/world.csv",
  "dvc/events/guardian_extended/2014-7-1_2016-6-30/uk-news.csv",
  "dvc/events/guardian_extended/2014-7-1_2016-6-30/us-news.csv",
  "dvc/events/guardian_extended/2015-7-1_2017-6-30/uk-news.csv",
  "dvc/events/guardian_extended/2015-7-1_2017-6-30/us-news.csv",
  "dvc/events/guardian_extended/2018-7-1_2020-6-30/uk-news.csv",
  "dvc/events/guardian_extended/2018-7-1_2020-6-30/us-news.csv",
  "dvc/events/guardian_extended/2018-7-1_2020-6-30/world.csv",
  "dvc/events/guardian_extended/2019-7-1_2021-6-30/uk-news.csv",
  "dvc/events/guardian_extended/2019-7-1_2021-6-30/us-news.csv",
  "dvc/events/guardian_extended/2020-7-1_2022-6-30/uk-news.csv",
  "dvc/events/guardian_extended/2019-7-1_2021-6-30/world.csv",
  "dvc/events/guardian_extended/2020-7-1_2022-6-30/us-news.csv",
  "dvc/events/guardian_extended/2020-7-1_2022-6-30/world.csv",
  #"dvc/events/guardian_extended/2021-7-1_2023-6-30/uk-news.csv",
  "dvc/events/guardian_extended/2021-7-1_2023-6-30/world.csv",
  "dvc/events/guardian_extended/2021-7-1_2023-6-30/us-news.csv",
]
processes: