evaluations:
  "random": [
    "dvc/evaluations/artificial_split/random",
    "dvc/evaluations/artificial_split/random_num_1",
    "dvc/evaluations/artificial_split/random_num_2",
    "dvc/evaluations/artificial_split/random_num_3",
    "dvc/evaluations/artificial_split/random_num_4",
  ]
  "constant": [
    "dvc/evaluations/artificial_split/constant"
  ]
  "TVD,L=180": [
    "dvc/evaluations/artificial_split/tvd180",
    "dvc/evaluations/artificial_split/tvd180_num_1",
    "dvc/evaluations/artificial_split/tvd180_num_2",
    "dvc/evaluations/artificial_split/tvd180_num_3",
    "dvc/evaluations/artificial_split/tvd180_num_4",
  ]
  "distilroberta,L=180": [
    "dvc/evaluations/artificial_split/distilroberta",
    "dvc/evaluations/artificial_split/distilroberta_num_1",
    "dvc/evaluations/artificial_split/distilroberta_num_2",
    "dvc/evaluations/artificial_split/distilroberta_num_3",
    "dvc/evaluations/artificial_split/distilroberta_num_4",
  ]
summary_path: "dvc/summaries/artificial_split"
xticks_format: "YY-MM"
rescale_models: True
