evaluations:
  "constant": [
    "dvc/evaluations/generated/constant",
    "dvc/evaluations/generated/constant_num_1",
    "dvc/evaluations/generated/constant_num_2",
    "dvc/evaluations/generated/constant_num_3",
    "dvc/evaluations/generated/constant_num_4",
  ]
  "random": [
    "dvc/evaluations/generated/random",
    "dvc/evaluations/generated/random_num_1",
    "dvc/evaluations/generated/random_num_2",
    "dvc/evaluations/generated/random_num_3",
    "dvc/evaluations/generated/random_num_4",
  ]
  "TVD,L=8": [
    "dvc/evaluations/generated/tvd8",
    "dvc/evaluations/generated/tvd8_num_1",
    "dvc/evaluations/generated/tvd8_num_2",
    "dvc/evaluations/generated/tvd8_num_3",
    "dvc/evaluations/generated/tvd8_num_4",
  ]
  "TVD,L=10": [
    "dvc/evaluations/generated/tvd10",
    "dvc/evaluations/generated/tvd10_num_1",
    "dvc/evaluations/generated/tvd10_num_2",
    "dvc/evaluations/generated/tvd10_num_3",
    "dvc/evaluations/generated/tvd10_num_4",
  ]
  "distilroberta,L=8": [
    "dvc/evaluations/generated/distilroberta",
    "dvc/evaluations/generated/distilroberta_num_1",
    "dvc/evaluations/generated/distilroberta_num_2",
    "dvc/evaluations/generated/distilroberta_num_3",
    "dvc/evaluations/generated/distilroberta_num_4",
  ]
summary_path: "dvc/summaries/generated"
xticks_format: "dd"
rescale_models: True
