evaluations:
  "random,L=180": [
    "dvc/evaluations/guardian_extended_no_sign/random",
    "dvc/evaluations/guardian_extended_no_sign/random_num_1",
    "dvc/evaluations/guardian_extended_no_sign/random_num_2",
    "dvc/evaluations/guardian_extended_no_sign/random_num_3",
    "dvc/evaluations/guardian_extended_no_sign/random_num_4",
  ]
  "TVD,L=180": [
    "dvc/evaluations/guardian_extended_no_sign/tvd_l180",
    "dvc/evaluations/guardian_extended_no_sign/tvd_l180_num_1",
    "dvc/evaluations/guardian_extended_no_sign/tvd_l180_num_2",
    "dvc/evaluations/guardian_extended_no_sign/tvd_l180_num_3",
    "dvc/evaluations/guardian_extended_no_sign/tvd_l180_num_4",
  ]
  "FF,embedding,L=180": [
    "dvc/evaluations/guardian_extended_no_sign/confusion_ff_embed_l180",
    "dvc/evaluations/guardian_extended_no_sign/confusion_ff_embed_l180_num_1",
    "dvc/evaluations/guardian_extended_no_sign/confusion_ff_embed_l180_num_2",
    "dvc/evaluations/guardian_extended_no_sign/confusion_ff_embed_l180_num_3",
    "dvc/evaluations/guardian_extended_no_sign/confusion_ff_embed_l180_num_4",
  ]
  "distilroberta1,L=180": [
    "dvc/evaluations/guardian_extended_no_sign/distilroberta",
    "dvc/evaluations/guardian_extended_no_sign/distilroberta_num_1",
    "dvc/evaluations/guardian_extended_no_sign/distilroberta_num_2",
    "dvc/evaluations/guardian_extended_no_sign/distilroberta_num_3",
    "dvc/evaluations/guardian_extended_no_sign/distilroberta_num_4",
  ]
summary_path: "dvc/summaries/guardian_extended_no_sign"
rescale_models: True
xticks_format: "YY-MM"
