evaluations:
  "TVD,L=90": [
    "dvc/evaluations/guardian_extended/tvd_l90",
    "dvc/evaluations/guardian_extended/tvd_l90_num_1",
    "dvc/evaluations/guardian_extended/tvd_l90_num_2",
    "dvc/evaluations/guardian_extended/tvd_l90_num_3",
    "dvc/evaluations/guardian_extended/tvd_l90_num_4",
  ]
  "TVD,L=180": [
    "dvc/evaluations/guardian_extended/tvd_l180",
    "dvc/evaluations/guardian_extended/tvd_l180_num_1",
    "dvc/evaluations/guardian_extended/tvd_l180_num_2",
    "dvc/evaluations/guardian_extended/tvd_l180_num_3",
    "dvc/evaluations/guardian_extended/tvd_l180_num_4",
  ]
  "FF,tfidf,L=90": [
    "dvc/evaluations/guardian_extended/confusion_ff_tfidf_l90",
    "dvc/evaluations/guardian_extended/confusion_ff_tfidf_l90_num_1",
    "dvc/evaluations/guardian_extended/confusion_ff_tfidf_l90_num_2",
    "dvc/evaluations/guardian_extended/confusion_ff_tfidf_l90_num_3",
    "dvc/evaluations/guardian_extended/confusion_ff_tfidf_l90_num_4",
  ]
  "FF,tfidf,L=180": [
    "dvc/evaluations/guardian_extended/confusion_ff_tfidf_l180",
    "dvc/evaluations/guardian_extended/confusion_ff_tfidf_l180_num_1",
    "dvc/evaluations/guardian_extended/confusion_ff_tfidf_l180_num_2",
    "dvc/evaluations/guardian_extended/confusion_ff_tfidf_l180_num_3",
    "dvc/evaluations/guardian_extended/confusion_ff_tfidf_l180_num_4",
  ]
  "FF,embedding,L=90": [
    "dvc/evaluations/guardian_extended/confusion_ff_embed_l90",
    "dvc/evaluations/guardian_extended/confusion_ff_embed_l90_num_1",
    "dvc/evaluations/guardian_extended/confusion_ff_embed_l90_num_2",
    "dvc/evaluations/guardian_extended/confusion_ff_embed_l90_num_3",
    "dvc/evaluations/guardian_extended/confusion_ff_embed_l90_num_4",
  ]
  "FF,embedding,L=180": [
    "dvc/evaluations/guardian_extended/confusion_ff_embed_l180",
    "dvc/evaluations/guardian_extended/confusion_ff_embed_l180_num_1",
    "dvc/evaluations/guardian_extended/confusion_ff_embed_l180_num_2",
    "dvc/evaluations/guardian_extended/confusion_ff_embed_l180_num_3",
    "dvc/evaluations/guardian_extended/confusion_ff_embed_l180_num_4",
  ]
summary_path: "dvc/summaries/guardian_extended"
top_n_delta: 3
show_max_tvd: True
#manual_events_path: "dvc/manual_events/guardian_extended.csv"
significant_events_path: "dvc/evaluations/guardian_extended/confusion_ff_embed_l180/deltas.csv"
rescale_models: True
xticks_format: "YY-MM"