name: Continous Integration Checks

on:
  pull_request:
    branches:
      - main

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.10.14"

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip setuptools wheel
          pip install -e ".[dev]"

      - name: Black Check
        run: black --check src/ tests/ --line-length 120

      - name: Flake8 Check
        run: flake8 src/ --max-line-length 120

      - name: Toml Sort Check
        run: toml-sort --check pyproject.toml

  unit_tests:
    name: Unit tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.10.14"

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip  setuptools wheel
          pip install -e ".[dev]"

      - name: Download English Dependencies
        run: |
          python -m spacy download en

      - name: Run tests
        run: pytest tests
